# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digital_prices', tinymce.models.HTMLField()),
                ('canvas_prices', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='PricingFrontPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
