# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-31 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='canvas_prices',
            new_name='prices',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='digital_prices',
        ),
        migrations.AddField(
            model_name='pricing',
            name='pricing_title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
