# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-18 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gdpr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('small_title', models.CharField(max_length=200)),
                ('gdpr_content', tinymce.models.HTMLField()),
            ],
        ),
    ]
