# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-02 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr_page_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdpr',
            name='consent_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='gdpr',
            name='stop_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
