# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-02 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_content_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='image_title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
