# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyVision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('vision', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='assets/images')),
            ],
        ),
        migrations.CreateModel(
            name='HomeFrontPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=200)),
                ('small_title', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='assets/images')),
            ],
        ),
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description_field', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='assets/images')),
            ],
        ),
        migrations.CreateModel(
            name='PhotographersCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_title', models.CharField(max_length=200)),
                ('description_field', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShootCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_title', models.CharField(max_length=200)),
                ('description_field', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='assets/images')),
            ],
        ),
    ]
