# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-02 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickToPayLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AlterField(
            model_name='companyvision',
            name='title',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='companyvision',
            name='vision',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='description_field',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='photographerscount',
            name='description_field',
            field=models.CharField(max_length=350),
        ),
    ]
