# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-03 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0002_auto_20180902_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='clicktopaylink',
            name='link_description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
