# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-11 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_page_content', '0002_auto_20180811_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='name',
            field=models.CharField(default='Lorena', max_length=200),
            preserve_default=False,
        ),
    ]
